### ISSUE TITLE
The server provider was unable to create your server (Digital Ocean provider.)

### ISSUE THREAD

**Issue by DougThwaites** [themsaid/forge-sdk#58]
> The server provider was unable to create your server

When creating a new server on Digital Ocean.

**Comment by DougThwaites** [comment]
If you are a new user to Digital Ocean this can be caused by if you have not yet added billing details to your Digital Ocean account.

Alternatively Digital Ocean have an initial droplet limit of 10 which you may have hit in which case just flick Digital Ocean a support ticket.

In my case however the issue was with the 'size' value I was posting to Forge. In the Forge API doc's and this SDK's readme it gives the example of human readable sizes such as "512MB", "1GB" etc which failed to create the server.

What worked in the end was logging into Forge and creating a new server and seeing what values Forge itself posts to itself internally as I imagine they are all pretty similar if not the same and noticed the size value for a "1GB" droplet was "01".

So with using "01" as the size value it successfully created the new Droplet.

Hope this helps someone.

And of course big thanks to @themsaid and any contributors for their hardword on this SDK.

**Comment by joshevensen** [comment]
I just got this error and found out that it was because I was trying to add a droplet to a region that DigitalOcean says is unavailable. The error from the SDK doesn't let you know this, but I decided to recreate everything via the GUI and got a more helpful error there saying the region is unavailable.

Just wanted to let others know in case they find this issue and have the same problem.
